
import './globals.css'
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { ArtistaContextProvider } from '@/provider/artistaProvider';



export const metadata = {
  title: 'Artistas ',
  description: 'Generated by cristian',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body >
        <Navbar />
        <ArtistaContextProvider>
          {children}
        </ArtistaContextProvider>
        <Footer />
      </body>
    </html>
  )
}